# Generated by Django 3.2.5 on 2021-08-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210822_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug_field',
            field=models.SlugField(editable=False, max_length=128, null=True, unique=True),
        ),
    ]
