# Generated by Django 3.2.5 on 2021-08-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpost_slug_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostcategory',
            name='slug_field',
            field=models.SlugField(editable=False, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='pub_date',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
