# Generated by Django 3.2.5 on 2021-08-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210826_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AlterField(
            model_name='postimage',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
